apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
    track: canary
  name: app-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        track: canary
      name: app
    spec:
      containers:
        - name: app
          image: kelseyhightower/app-healthz:2.0.0
          imagePullPolicy: Always
          env:
            - name: HTTP_ADDR
              value: "0.0.0.0:80"
            - name: DATABASE_HOST
              value: "mysql:3306"
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app
                  key: vault-token 
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
