apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
      name: vault
    spec:
      containers:
        - name: vault
          image: kelseyhightower/vault:0.6.0
          args:
            - "server"
            - "-dev"
            - "-dev-listen-address=0.0.0.0:8200"
          ports:
            - name: http
              containerPort: 8200
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
