apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
      name: vault
    spec:
      containers:
        - name: vault
          image: kelseyhightower/vault:0.6.0
          args:
            - "server"
            - "-config=/etc/vault/vault.hcl"
          ports:
            - name: http
              containerPort: 8200
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: "vault-conf"
              mountPath: "/etc/vault"
            - name: "vault-data"
              mountPath: "/var/lib/vault"
      volumes:
        - name: "vault-data"
          gcePersistentDisk:
            pdName: vault-data
            fsType: ext4
        - name: "vault-conf"
          configMap:
            name: "vault-conf"
            items:
              - key: "vault.hcl"
                path: "vault.hcl"
